"""Deterministic ECF generation, validation, and guarded updates."""

from __future__ import annotations

import difflib
import hashlib
import json
import os
import re
from collections.abc import Mapping
from pathlib import Path, PureWindowsPath

from lxml import etree

from evm.dependencies import dependency_library_locations
from evm.errors import EvmError
from evm.filesystem import atomic_write
from evm.lockfile import LOCK_NAME, LockFile, ensure_lock_matches, load_lock
from evm.model import Condition, Project, Target

ECF_NAMESPACE = "http://www.eiffel.com/developers/xml/configuration-1-23-0"
SUPPORTED_ECF_NAMESPACES = frozenset(
    {
        "http://www.eiffel.com/developers/xml/configuration-1-18-0",
        ECF_NAMESPACE,
    }
)
XSI_NAMESPACE = "http://www.w3.org/2001/XMLSchema-instance"
_MARKER_RE = re.compile(
    rb"Generated by EVM; input-fingerprint: ([0-9a-f]{64}); content-fingerprint: ([0-9a-f]{64})"
)
_CONDITIONAL_CLUSTER_INDEX_OFFSET = 1000
_ECF_GROUP_ELEMENTS = frozenset({"assembly", "cluster", "library", "precompile"})


def generate_ecf(project: Project, lock: LockFile | None = None) -> bytes:
    """Return canonical, deterministic ECF bytes for a normalized project."""
    selected_lock = _dependency_lock(project, lock)
    root = etree.Element(
        f"{{{ECF_NAMESPACE}}}system",
        nsmap={None: ECF_NAMESPACE, "xsi": XSI_NAMESPACE},
        name=project.name,
        uuid=project.uuid,
    )
    root.set(
        f"{{{XSI_NAMESPACE}}}schemaLocation",
        f"{ECF_NAMESPACE} {ECF_NAMESPACE}.xsd",
    )
    if project.kind == "library":
        root.set("library_target", "default")
    for target in project.targets:
        _add_target(root, project, target, selected_lock)
    complete_overlay = _apply_ecf_includes(root, project)
    if complete_overlay is not None:
        return _serialize(complete_overlay)
    _validate_unique_group_names(root)
    content = _serialize(root)
    input_fingerprint = _project_fingerprint(project, selected_lock)
    content_fingerprint = hashlib.sha256(content).hexdigest()
    root.insert(
        0,
        etree.Comment(
            " Generated by EVM; "
            f"input-fingerprint: {input_fingerprint}; "
            f"content-fingerprint: {content_fingerprint} "
        ),
    )
    return _serialize(root)


def ensure_managed_ecf(
    project: Project,
    *,
    regenerate: bool = False,
    lock: LockFile | None = None,
) -> bool:
    """Create or update managed ECF, rejecting unapproved manual changes."""
    if not project.ecf_managed:
        validate_ecf(project.ecf_path)
        return False
    expected = managed_ecf_bytes(project, regenerate=regenerate, lock=lock)
    if not project.ecf_path.exists():
        atomic_write(project.ecf_path, expected)
        return True
    existing = project.ecf_path.read_bytes()
    if existing == expected:
        return False
    atomic_write(project.ecf_path, expected)
    return True


def managed_ecf_bytes(
    project: Project,
    *,
    regenerate: bool = False,
    lock: LockFile | None = None,
) -> bytes:
    expected = generate_ecf(project, lock)
    if (
        project.ecf_path.exists()
        and project.ecf_path.read_bytes() != expected
        and not regenerate
        and not _is_untouched_managed_ecf(project.ecf_path.read_bytes())
    ):
        raise EvmError(
            "managed ECF was modified outside EVM\n\n"
            "inspect:\n  evm explain --ecf-diff\n\n"
            "overwrite explicitly:\n  evm build --regenerate-ecf"
        )
    return expected


def validate_ecf(path: Path) -> None:
    tree = parse_ecf(path)
    if not tree.xpath("/*[local-name()='system']/*[local-name()='target']"):
        raise EvmError(f"invalid ECF {path}: no targets")


def prepare_legacy_ecf(
    project: Project,
    variable_roots: Mapping[str, Path] | None = None,
) -> Path:
    """Stage a portable legacy ECF when native path separators require it."""
    tree = parse_ecf(project.ecf_path)
    locations = tree.xpath("//*[@location]")
    if not any("\\" in node.get("location", "") for node in locations):
        return project.ecf_path
    destination = project.state_directory / "tmp" / "legacy" / project.ecf_path.name
    for node in locations:
        location = node.get("location")
        if location is not None:
            node.set(
                "location",
                _portable_legacy_location(
                    location,
                    project.ecf_path.parent,
                    destination.parent,
                    variable_roots or {},
                ),
            )
    atomic_write(
        destination,
        etree.tostring(tree, encoding="UTF-8", xml_declaration=True),
    )
    return destination


def _portable_legacy_location(
    location: str,
    source: Path,
    destination: Path,
    variable_roots: Mapping[str, Path],
) -> str:
    portable = location.replace("\\", "/")
    if "$" in portable or Path(portable).is_absolute() or PureWindowsPath(location).is_absolute():
        return _available_legacy_location(portable, variable_roots)
    return Path(os.path.relpath(source / portable, destination)).as_posix()


def _available_legacy_location(location: str, variable_roots: Mapping[str, Path]) -> str:
    expanded = Path(_expand_legacy_variables(location, variable_roots))
    if expanded.is_file() or not location.endswith("-safe.ecf"):
        return location
    fallback = location.removesuffix("-safe.ecf") + ".ecf"
    fallback_path = Path(_expand_legacy_variables(fallback, variable_roots))
    return fallback if fallback_path.is_file() else location


def _expand_legacy_variables(location: str, variable_roots: Mapping[str, Path]) -> str:
    expanded = os.path.expandvars(location)
    for name, root in variable_roots.items():
        expanded = expanded.replace(f"${{{name}}}", str(root)).replace(f"${name}", str(root))
    return expanded


def parse_ecf(path: Path) -> etree._ElementTree:
    """Parse a supported ECF without resolving external entities."""
    try:
        tree = etree.parse(
            str(path),
            parser=etree.XMLParser(resolve_entities=False, no_network=True),
        )
    except (OSError, etree.XMLSyntaxError) as error:
        raise EvmError(f"invalid ECF {path}: {error}") from error
    document_root = tree.getroot()
    namespace = etree.QName(document_root).namespace
    if namespace not in SUPPORTED_ECF_NAMESPACES:
        supported = ", ".join(sorted(SUPPORTED_ECF_NAMESPACES))
        raise EvmError(f"unsupported ECF namespace {namespace!r}; supported: {supported}")
    if etree.QName(document_root).localname != "system":
        raise EvmError(f"unsupported ECF root in {path}: expected <system>")
    return tree


def semantic_summary(data: bytes) -> dict[str, object]:
    """Extract the stage-one ECF semantics used for comparisons."""
    try:
        root = etree.fromstring(
            data,
            parser=etree.XMLParser(resolve_entities=False, no_network=True),
        )
    except etree.XMLSyntaxError as error:
        raise EvmError(f"invalid ECF: {error}") from error
    return _semantic_element(root)


def semantic_diff(project: Project) -> str:
    expected = semantic_summary(generate_ecf(project))
    if not project.ecf_path.exists():
        return f"ECF is missing: {project.ecf_path}\n"
    current = semantic_summary(project.ecf_path.read_bytes())
    if current == expected:
        return "No semantic differences.\n"
    current_text = json.dumps(current, indent=2, sort_keys=True).splitlines()
    expected_text = json.dumps(expected, indent=2, sort_keys=True).splitlines()
    return (
        "\n".join(
            difflib.unified_diff(
                current_text,
                expected_text,
                fromfile=str(project.ecf_path),
                tofile="expected from Eiffel.toml",
                lineterm="",
            )
        )
        + "\n"
    )


def _apply_ecf_includes(
    generated_root: etree._Element,
    project: Project,
) -> etree._Element | None:
    complete_overlay: etree._Element | None = None
    for include_path in project.ecf_includes:
        overlay_root = _parse_ecf_include(include_path)
        if etree.QName(overlay_root).localname == "system":
            if complete_overlay is not None or len(project.ecf_includes) != 1:
                raise EvmError("a complete-system ECF include must be the only ecf.include")
            if project.ecf_managed:
                raise EvmError("a complete-system ECF include is only valid in legacy mode")
            _validate_complete_overlay(overlay_root, project, include_path)
            complete_overlay = overlay_root
            continue
        _merge_ecf_fragment(generated_root, overlay_root, include_path)
    return complete_overlay


def _parse_ecf_include(path: Path) -> etree._Element:
    try:
        data = path.read_bytes()
    except OSError as error:
        raise EvmError(f"cannot read ECF include {path}: {error}") from error
    try:
        root = etree.fromstring(
            data,
            parser=etree.XMLParser(resolve_entities=False, no_network=True),
        )
    except etree.XMLSyntaxError as error:
        raise EvmError(f"invalid ECF include {path}: {error}") from error
    namespace = etree.QName(root).namespace
    if namespace not in SUPPORTED_ECF_NAMESPACES:
        supported = ", ".join(sorted(SUPPORTED_ECF_NAMESPACES))
        raise EvmError(
            f"unsupported ECF include namespace {namespace!r} in {path}; supported: {supported}"
        )
    if etree.QName(root).localname not in {"system", "ecf-overlay"}:
        raise EvmError(f"ECF include {path} must contain <system> or <ecf-overlay>")
    return root


def _validate_complete_overlay(
    overlay: etree._Element,
    project: Project,
    path: Path,
) -> None:
    if overlay.get("name") != project.name:
        raise EvmError(f"ECF include {path} has a system name that conflicts with project.name")
    if overlay.get("uuid") != project.uuid:
        raise EvmError(f"ECF include {path} has a UUID that conflicts with project.uuid")


def _merge_ecf_fragment(
    generated_root: etree._Element,
    fragment: etree._Element,
    path: Path,
) -> None:
    targets = {
        target.get("name"): target
        for target in generated_root
        if isinstance(target.tag, str) and etree.QName(target).localname == "target"
    }
    for child in fragment:
        if not isinstance(child.tag, str):
            continue
        if etree.QName(child).localname != "target":
            generated_root.append(_copy_element(child))
            continue
        name = child.get("name")
        if not name or name not in targets:
            raise EvmError(f"ECF include {path} refers to unknown target {name!r}")
        target = targets[name]
        for attribute, value in child.attrib.items():
            if attribute == "name":
                continue
            existing = target.get(attribute)
            if attribute == "extends" and existing != value:
                raise EvmError(
                    f"ECF include {path} conflicts with target {name!r} attribute {attribute!r}"
                )
            if existing is not None and existing != value:
                raise EvmError(
                    f"ECF include {path} conflicts with target {name!r} attribute {attribute!r}"
                )
            target.set(attribute, value)
        for target_child in child:
            if isinstance(target_child.tag, str):
                local_name = etree.QName(target_child).localname
                if local_name in {"root", "cluster"}:
                    raise EvmError(
                        f"ECF include {path} conflicts with high-level "
                        f"{local_name} in target {name!r}"
                    )
                target.append(_copy_element(target_child))


def _copy_element(element: etree._Element) -> etree._Element:
    return etree.fromstring(etree.tostring(element))


def _validate_unique_group_names(system: etree._Element) -> None:
    for target in system:
        if not isinstance(target.tag, str) or etree.QName(target).localname != "target":
            continue
        groups: dict[str, str] = {}
        for child in target:
            if not isinstance(child.tag, str):
                continue
            group_kind = etree.QName(child).localname
            group_name = child.get("name")
            if group_kind not in _ECF_GROUP_ELEMENTS or group_name is None:
                continue
            previous_kind = groups.get(group_name)
            if previous_kind is not None:
                raise EvmError(
                    f"ECF target {target.get('name')!r} contains duplicate group name "
                    f"{group_name!r} for {previous_kind} and {group_kind}"
                )
            groups[group_name] = group_kind


def _add_target(
    root: etree._Element,
    project: Project,
    target: Target,
    lock: LockFile | None,
) -> None:
    attributes = {"name": target.name}
    if target.extends is not None:
        attributes["extends"] = target.extends
    node = etree.SubElement(root, f"{{{ECF_NAMESPACE}}}target", **attributes)
    if target.root is None and target.extends is None:
        etree.SubElement(node, f"{{{ECF_NAMESPACE}}}root", all_classes="true")
    elif target.root is not None:
        etree.SubElement(
            node,
            f"{{{ECF_NAMESPACE}}}root",
            **{"class": target.root.class_name, "feature": target.root.feature},
        )
    _add_requirements(node, project)
    _add_conditional_externals(node, project, target)
    if target.extends is None:
        _add_runtime_libraries(node)
    _add_autotest_library(node, project, target)
    _add_dependency_libraries(node, project, target, lock)
    _add_clusters(node, project, target)


def _add_autotest_library(
    target_element: etree._Element,
    project: Project,
    target: Target,
) -> None:
    if (
        project.test is None
        or project.test.runner != "autotest"
        or project.test.target != target.name
    ):
        return
    etree.SubElement(
        target_element,
        f"{{{ECF_NAMESPACE}}}library",
        name="testing",
        location="${ISE_LIBRARY}/library/testing/testing.ecf",
        readonly="true",
    )


def _add_dependency_libraries(
    target_element: etree._Element,
    project: Project,
    target: Target,
    lock: LockFile | None,
) -> None:
    if lock is None:
        return
    include_development = target.name in {"test", "development"} or any(
        source == "tests" or source.startswith("tests/") for source in target.sources
    )
    for name, location in dependency_library_locations(
        project,
        lock,
        include_development=include_development,
    ):
        package = lock.package(name)
        if target.extends is not None and not package.development:
            continue
        etree.SubElement(
            target_element,
            f"{{{ECF_NAMESPACE}}}library",
            name=name,
            location=location,
            readonly="true",
        )


def _add_requirements(target: etree._Element, project: Project) -> None:
    requirements = dict(project.requires)
    if "standard" in requirements:
        etree.SubElement(
            target,
            f"{{{ECF_NAMESPACE}}}option",
            syntax="standard",
        )
    if project.kind == "application":
        etree.SubElement(
            target,
            f"{{{ECF_NAMESPACE}}}setting",
            name="console_application",
            value="true",
        )
    capability_values = {
        key: requirements[key] for key in ("concurrency", "void-safety") if key in requirements
    }
    if capability_values:
        capability = etree.SubElement(target, f"{{{ECF_NAMESPACE}}}capability")
        if "concurrency" in capability_values:
            etree.SubElement(
                capability,
                f"{{{ECF_NAMESPACE}}}concurrency",
                use=capability_values["concurrency"],
            )
        if "void-safety" in capability_values:
            etree.SubElement(
                capability,
                f"{{{ECF_NAMESPACE}}}void_safety",
                use=capability_values["void-safety"],
            )


def _add_conditional_externals(
    target_element: etree._Element,
    project: Project,
    target: Target,
) -> None:
    for condition in project.conditions:
        if condition.target != target.name:
            continue
        for external in condition.external_objects:
            tag = "external_object" if not external.startswith("-l") else "external_linker_flag"
            attribute = "location" if tag == "external_object" else "value"
            item = etree.SubElement(
                target_element,
                f"{{{ECF_NAMESPACE}}}{tag}",
                **{attribute: external},
            )
            _add_condition(item, condition)


def _add_clusters(
    target_element: etree._Element,
    project: Project,
    target: Target,
) -> None:
    for index, source in enumerate(target.sources):
        etree.SubElement(
            target_element,
            f"{{{ECF_NAMESPACE}}}cluster",
            name=_cluster_name(target.name, source, index),
            location=source,
            recursive="true",
        )
    for condition_index, condition in enumerate(project.conditions):
        if condition.target != target.name:
            continue
        for source_index, source in enumerate(condition.sources):
            cluster = etree.SubElement(
                target_element,
                f"{{{ECF_NAMESPACE}}}cluster",
                name=_cluster_name(
                    target.name,
                    source,
                    condition_index + source_index + _CONDITIONAL_CLUSTER_INDEX_OFFSET,
                ),
                location=source,
                recursive="true",
            )
            _add_condition(cluster, condition)


def _add_runtime_libraries(target: etree._Element) -> None:
    """Select the native root runtime without tying the project to one compiler."""
    ise = etree.SubElement(
        target,
        f"{{{ECF_NAMESPACE}}}library",
        name="base",
        location="${ISE_LIBRARY}/library/base/base.ecf",
        readonly="true",
    )
    ise_condition = etree.SubElement(ise, f"{{{ECF_NAMESPACE}}}condition")
    etree.SubElement(
        ise_condition,
        f"{{{ECF_NAMESPACE}}}custom",
        name="GOBO_EIFFEL",
        excluded_value="ge",
    )
    gobo = etree.SubElement(
        target,
        f"{{{ECF_NAMESPACE}}}library",
        name="free_elks",
        location="${GOBO}/library/free_elks/library_${GOBO_EIFFEL}.ecf",
        readonly="true",
    )
    gobo_condition = etree.SubElement(gobo, f"{{{ECF_NAMESPACE}}}condition")
    etree.SubElement(
        gobo_condition,
        f"{{{ECF_NAMESPACE}}}custom",
        name="GOBO_EIFFEL",
        value="ge",
    )


def _add_condition(parent: etree._Element, condition: Condition) -> None:
    node = etree.SubElement(parent, f"{{{ECF_NAMESPACE}}}condition")
    values = dict(condition.when)
    if "os" in values:
        platform = "macintosh" if values["os"] in {"macos", "darwin"} else values["os"]
        etree.SubElement(node, f"{{{ECF_NAMESPACE}}}platform", value=platform)
    if "mode" in values:
        build = "finalize" if values["mode"] == "release" else "workbench"
        etree.SubElement(node, f"{{{ECF_NAMESPACE}}}build", value=build)
    for key in ("architecture", "compiler"):
        if key in values:
            etree.SubElement(
                node,
                f"{{{ECF_NAMESPACE}}}custom",
                name=f"evm_{key}",
                value=values[key],
            )


def _cluster_name(target: str, source: str, index: int) -> str:
    raw = re.sub(r"[^A-Za-z0-9_]", "_", source.strip("./").replace("/", "_"))
    raw = raw.strip("_") or "sources"
    return f"{target}_{raw}_{index}"


def _project_fingerprint(project: Project, lock: LockFile | None) -> str:
    value = {
        "name": project.name,
        "version": project.version,
        "kind": project.kind,
        "uuid": project.uuid,
        "test": None
        if project.test is None
        else {"target": project.test.target, "runner": project.test.runner},
        "targets": [
            {
                "name": item.name,
                "root": None if item.root is None else [item.root.class_name, item.root.feature],
                "sources": item.sources,
                "extends": item.extends,
            }
            for item in project.targets
        ],
        "conditions": [
            {
                "target": item.target,
                "when": item.when,
                "sources": item.sources,
                "external_objects": item.external_objects,
            }
            for item in project.conditions
        ],
        "requires": project.requires,
        "dependencies": None
        if lock is None
        else [
            {
                "name": package.name,
                "version": package.version,
                "source": package.source,
                "revision": package.revision,
                "tree": package.tree,
                "checksum": package.checksum,
                "ecf": package.ecf,
                "path": package.path,
                "development": package.development,
                "patched": package.patched,
            }
            for package in lock.packages
        ],
    }
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()


def _dependency_lock(project: Project, lock: LockFile | None) -> LockFile | None:
    if not project.dependencies:
        return None
    selected = lock or load_lock(project.directory / LOCK_NAME)
    ensure_lock_matches(project, selected)
    return selected


def _semantic_element(element: etree._Element) -> dict[str, object]:
    children = [_semantic_element(child) for child in element if isinstance(child.tag, str)]
    children.sort(key=lambda item: json.dumps(item, sort_keys=True))
    result: dict[str, object] = {
        "element": etree.QName(element).localname,
        "attributes": {
            etree.QName(name).localname: value for name, value in sorted(element.attrib.items())
        },
        "children": children,
    }
    text = (element.text or "").strip()
    if text:
        result["text"] = text
    return result


def _is_untouched_managed_ecf(data: bytes) -> bool:
    match = _MARKER_RE.search(data)
    if match is None:
        return False
    try:
        root = etree.fromstring(
            data,
            parser=etree.XMLParser(resolve_entities=False, no_network=True),
        )
    except etree.XMLSyntaxError:
        return False
    marker_comments = root.xpath("./comment()[contains(., 'Generated by EVM;')]")
    if len(marker_comments) != 1:
        return False
    root.remove(marker_comments[0])
    actual = hashlib.sha256(_serialize(root)).hexdigest().encode()
    return actual == match.group(2)


def _serialize(root: etree._Element) -> bytes:
    etree.indent(root, space="    ")
    return etree.tostring(
        root,
        encoding="UTF-8",
        xml_declaration=True,
        pretty_print=True,
    )
